[project]
name = "music-collection-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["click>=8.1.7", "mutagen>=1.47.0"]

[dependency-groups]
dev = ["nuitka>=2.5.3"]
